/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.Admin;

import static business.role.Role.RoleType.Student;
import business.student.accomodation.Permanent;
import business.student.registration.Student;
import business.student.registration.StudentDirectory;
import java.util.ArrayList;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JSplitPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mayurimore
 */
public class manageStudentRegistration extends javax.swing.JPanel {
//kugiygygyigi
    /**
     * Creates new form manageStudentRegistration
     */
    DefaultTableModel model;
    JSplitPane jSplitPane1;
    StudentDirectory studentHistory;
    Student student;
    public manageStudentRegistration(JSplitPane jSplitPane1, StudentDirectory studentHistory) {
        initComponents();
        this.jSplitPane1 = jSplitPane1;
        this.studentHistory = studentHistory;
        
        ArrayList<Student> studentList = studentHistory.getHistory();
        
      
       
        tblRegistrationRequest.setModel(model);
        
        model.addColumn("First Name");
        model.addColumn("Last NAmne");
        model.addColumn("Email ID");
        model.addColumn("Proof");
        model.addColumn("Status");
        
        
        viewRequestList(studentList);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRegistrationRequest = new javax.swing.JTable();
        btnViewRequests = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Manage Student Registration");

        tblRegistrationRequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblRegistrationRequest);

        btnViewRequests.setText("View Requests");
        btnViewRequests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewRequestsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(282, 282, 282)
                        .addComponent(btnViewRequests)))
                .addContainerGap(132, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnViewRequests)
                .addContainerGap(104, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewRequestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewRequestsActionPerformed
        // TODO add your handling code here:
        
    
    }//GEN-LAST:event_btnViewRequestsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnViewRequests;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblRegistrationRequest;
    // End of variables declaration//GEN-END:variables


public void viewRequestList(ArrayList<Student> studentList) {
    
        DefaultTableModel model = (DefaultTableModel) tblRegistrationRequest.getModel();
        model.setRowCount(0);
        
        for (Student student : studentList) {
            
                Object[] row = new Object[4];
                row[0] = student;
                row[1] = student.getFirstName();
                row[2] = student.getLastName();
                row[3] = student.getEmailAddress();
                
                model.addRow(row);
            }
        
            
             
            
           
        }
    }




